name: 📝 New Blog Post
description: Create a new blog post from this issue
title: ""
labels: ["blog"]
body:
  - type: markdown
    attributes:
      value: |
        ## Write Your Blog Post
        Fill in the details below. After you submit, the post will be automatically published.
        
  - type: textarea
    id: frontmatter
    attributes:
      label: Post Metadata
      description: Fill in your post description and tags
      value: |
        ---
        description: 
        tags: []
        ---
    validations:
      required: true
      
  - type: textarea
    id: content
    attributes:
      label: Blog Content (Markdown)
      description: Write your blog post content here
      placeholder: |
        ## Introduction
        
        Your content here...
    validations:
      required: true
      
  - type: checkboxes
    id: draft
    attributes:
      label: Publishing Options
      options:
        - label: Save as draft (don't publish yet)